/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.prisustvo;

import domen.Grupa;
import domen.Prisustvo;
import domen.Trener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.TableModelPrisustvo;
import java.util.logging.Level;
import java.util.logging.Logger;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPregledPrisustva extends javax.swing.JDialog {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    /**
     * Creates new form FrmPregledPrisustva
     */
    public FrmPregledPrisustva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        popuniCombo();
        popuniTabelu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPregled = new javax.swing.JPanel();
        jScrollPanePregled = new javax.swing.JScrollPane();
        jTablePregled = new javax.swing.JTable();
        jLabelGrupa = new javax.swing.JLabel();
        jComboBoxGrupa = new javax.swing.JComboBox<>();
        jButtonPretragaGrupa = new javax.swing.JButton();
        jButtonSveGrupe = new javax.swing.JButton();
        jButtonPretragaDatum = new javax.swing.JButton();
        jLabelDatum = new javax.swing.JLabel();
        jDateChooserDatum = new com.toedter.calendar.JDateChooser();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled prisustva");

        jPanelPregled.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregled prisustva članova"));

        jTablePregled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePregled.setViewportView(jTablePregled);

        jLabelGrupa.setText("Grupa:");

        jComboBoxGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPretragaGrupa.setText("Pretraga po grupi");
        jButtonPretragaGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaGrupaActionPerformed(evt);
            }
        });

        jButtonSveGrupe.setText("Svi članovi trenera");
        jButtonSveGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSveGrupeActionPerformed(evt);
            }
        });

        jButtonPretragaDatum.setText("Pretraga po datumu");
        jButtonPretragaDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaDatumActionPerformed(evt);
            }
        });

        jLabelDatum.setText("Datum:");

        javax.swing.GroupLayout jPanelPregledLayout = new javax.swing.GroupLayout(jPanelPregled);
        jPanelPregled.setLayout(jPanelPregledLayout);
        jPanelPregledLayout.setHorizontalGroup(
            jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregledLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePregled, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addComponent(jButtonSveGrupe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPregledLayout.createSequentialGroup()
                        .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPregledLayout.createSequentialGroup()
                                .addComponent(jLabelGrupa)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGrupa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonPretragaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPretragaDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPregledLayout.createSequentialGroup()
                                .addComponent(jLabelDatum)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelPregledLayout.setVerticalGroup(
            jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPregledLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGrupa)
                        .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDatum))
                    .addComponent(jDateChooserDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPregledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPretragaGrupa)
                    .addComponent(jButtonPretragaDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSveGrupe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePregled, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonPretragaGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaGrupaActionPerformed
        pretrazi();
    }//GEN-LAST:event_jButtonPretragaGrupaActionPerformed

    private void jButtonSveGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSveGrupeActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jButtonSveGrupeActionPerformed

    private void jButtonPretragaDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaDatumActionPerformed
       pretraziPoDatumu();
    }//GEN-LAST:event_jButtonPretragaDatumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonPretragaDatum;
    private javax.swing.JButton jButtonPretragaGrupa;
    private javax.swing.JButton jButtonSveGrupe;
    private javax.swing.JComboBox<Object> jComboBoxGrupa;
    private com.toedter.calendar.JDateChooser jDateChooserDatum;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelGrupa;
    private javax.swing.JPanel jPanelPregled;
    private javax.swing.JScrollPane jScrollPanePregled;
    private javax.swing.JTable jTablePregled;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        ServerskiOdgovor so = Kontroler.getInstance().vratiListuPrisustva();
        ArrayList<Prisustvo> listaPrisustva = (ArrayList<Prisustvo>) so.getOdgovor();
        ArrayList<Prisustvo> prikaz = new ArrayList<>();

        for (Prisustvo prisustvo : listaPrisustva) {

            if (ulogovanTrener.getTrenerID().equals(prisustvo.getTrening().getTrener().getTrenerID())) {
                prikaz.add(prisustvo);
            }
        }

        TableModelPrisustvo tmp = new TableModelPrisustvo(prikaz);
        jTablePregled.setModel(tmp);
    }

    private void pretrazi() {

        Grupa grupa = (Grupa) jComboBoxGrupa.getSelectedItem();
        
         if(grupa == null){
            JOptionPane.showMessageDialog(this, "Trener ne trenira nijednu grupu!! Napravi novu grupu!!");
            return;
        }
        ServerskiOdgovor so = Kontroler.getInstance().pretraziPrisustva();
        ArrayList<Prisustvo> listaPrisustva = (ArrayList<Prisustvo>) so.getOdgovor();
        ArrayList<Prisustvo> prikaz = new ArrayList<>();

        for (Prisustvo prisustvo : listaPrisustva) {
            
            if (ulogovanTrener.getTrenerID().equals(prisustvo.getTrening().getTrener().getTrenerID())) {

                if (grupa.getGrupaID().equals(prisustvo.getClan().getGrupa().getGrupaID()) ) {
                    prikaz.add(prisustvo);
                }

            }
        }

        TableModelPrisustvo tmp = (TableModelPrisustvo) jTablePregled.getModel();
        tmp.setListaPrisustva(prikaz);
    }

    private void popuniCombo() {
        jComboBoxGrupa.removeAllItems(); //uklanjanje default vrednosti

        ServerskiOdgovor so = Kontroler.getInstance().vratiListuGrupa();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();

        for (Grupa grupa : listaGrupa) {

            if (grupa.getTrener().getTrenerID().equals(ulogovanTrener.getTrenerID())) {
                jComboBoxGrupa.addItem(grupa);
            }

        }
    }

    private void pretraziPoDatumu() {
        
        Date datum = jDateChooserDatum.getDate();
        ServerskiOdgovor so = Kontroler.getInstance().pretraziPrisustva();
        ArrayList<Prisustvo> listaPrisustva = (ArrayList<Prisustvo>) so.getOdgovor();
        ArrayList<Prisustvo> prikaz = new ArrayList<>();

        for (Prisustvo prisustvo : listaPrisustva) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                Date da = prisustvo.getTrening().getDatumVreme();
                String dat = sdf.format(da);
                Date datu = sdf.parse(dat);

                if (ulogovanTrener.getTrenerID().equals(prisustvo.getTrening().getTrener().getTrenerID())) {
                    if (datu.equals(datum)) {
                         prikaz.add(prisustvo);
                    }
                }

            } catch (ParseException ex) {
                Logger.getLogger(FrmPregledPrisustva.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Greška sa formatom datuma!!");
            }
                }
        
        TableModelPrisustvo tmp = (TableModelPrisustvo) jTablePregled.getModel();
        tmp.setListaPrisustva(prikaz);
    }
}
