/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.grupa;

import domen.Grupa;
import domen.Trener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.TableModelGrupa;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrikazGrupe extends javax.swing.JDialog {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    public void setUlogovanTrener(Trener ulogovanTrener) {
        this.ulogovanTrener = ulogovanTrener;
    }

    public Trener getUlogovanTrener() {
        return ulogovanTrener;
    }

    /**
     * Creates new form FrmPrikazGrupe
     */
    public FrmPrikazGrupe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        

        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrikaz = new javax.swing.JPanel();
        jScrollPanePrikaz = new javax.swing.JScrollPane();
        jTablePrikaz = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonSvoje = new javax.swing.JButton();
        jButtonGrupe = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz grupa");

        jPanelPrikaz.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaz grupa"));

        jTablePrikaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePrikaz.setViewportView(jTablePrikaz);

        jButtonObrisi.setText("Obriši grupu");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonSvoje.setText("Prikaži svoje grupe");
        jButtonSvoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSvojeActionPerformed(evt);
            }
        });

        jButtonGrupe.setText("Prikaži sve grupe");
        jButtonGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrupeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrikazLayout = new javax.swing.GroupLayout(jPanelPrikaz);
        jPanelPrikaz.setLayout(jPanelPrikazLayout);
        jPanelPrikazLayout.setHorizontalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePrikaz)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrikazLayout.createSequentialGroup()
                        .addComponent(jButtonSvoje, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jButtonGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPrikazLayout.setVerticalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addComponent(jScrollPanePrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSvoje)
                    .addComponent(jButtonGrupe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonObrisi)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNazad)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int red = jTablePrikaz.getSelectedRow();

        if (red != -1) {

            TableModelGrupa tmg = (TableModelGrupa) jTablePrikaz.getModel();
            Grupa grupa = tmg.uzmiGrupu(red);
            int brojClanovaGrupe = grupa.getBrojClanova();

            if (ulogovanTrener.getTrenerID().equals(grupa.getTrener().getTrenerID())) {

                if (brojClanovaGrupe == 0) {

                    Long grupaID = (Long) jTablePrikaz.getValueAt(red, 0);
                    tmg.obrisiGrupu(red);

                    Grupa obrisana = new Grupa();
                    obrisana.setGrupaID(grupaID);
                    ServerskiOdgovor so = Kontroler.getInstance().obrisiGrupu(obrisana);

                    if (so.isUspesnost()) {
                        JOptionPane.showMessageDialog(this, "Sistem je obrisao izabranu grupu!!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem nije obrisao izabranu grupu!!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Trener može obrisati samo grupu koja nema članove!!");
                    return;
                }

            } else {
                JOptionPane.showMessageDialog(this, "Trener može obrisati samo svoju grupu!!");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Označite grupu za brisanje!!");
            return;
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrupeActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jButtonGrupeActionPerformed

    private void jButtonSvojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSvojeActionPerformed
        pretraga();
    }//GEN-LAST:event_jButtonSvojeActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGrupe;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSvoje;
    private javax.swing.JPanel jPanelPrikaz;
    private javax.swing.JScrollPane jScrollPanePrikaz;
    private javax.swing.JTable jTablePrikaz;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        //Lista grupa treba da se napravi - preko kontrolera
        //Kad dobijemo listu grupa, tableModel treba da zna za tu listu - treba nam konstruktor(parametarski sa listom grupa) i set i get metoda u TM

        ServerskiOdgovor so = Kontroler.getInstance().vratiListuGrupa();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();

        TableModelGrupa tmg = new TableModelGrupa(listaGrupa);
        jTablePrikaz.setModel(tmg);

    }

    private void pretraga() {
        ServerskiOdgovor so = Kontroler.getInstance().pretraziGrupe();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();
        ArrayList<Grupa> prikaz = new ArrayList<>();

        for (Grupa grupa : listaGrupa) {
            if (ulogovanTrener.getTrenerID().equals(grupa.getTrener().getTrenerID())) {
                prikaz.add(grupa);
            }
        }

        TableModelGrupa tmg = new TableModelGrupa(prikaz);
        jTablePrikaz.setModel(tmg);
    }

}
