/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.trening;

import domen.Clan;
import domen.Trening;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.TableModelTrening;
import sesija.SesijaClan;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrikazTreningaClan extends javax.swing.JDialog {

    private Clan ulogovanClan = SesijaClan.getInstance().getClan();

    /**
     * Creates new form FrmPrikazTreningaClan
     */
    public FrmPrikazTreningaClan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrikaz = new javax.swing.JPanel();
        jDateChooserPretraga = new com.toedter.calendar.JDateChooser();
        jLabelPretraga = new javax.swing.JLabel();
        jButtonPretraga = new javax.swing.JButton();
        jScrollPanePretraga = new javax.swing.JScrollPane();
        jTablePretraga = new javax.swing.JTable();
        jButtonTreninzi = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz treninga - član");

        jPanelPrikaz.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaz treninga - član"));

        jLabelPretraga.setText("Pretraži trening po datumu: ");

        jButtonPretraga.setText("Pretraga");
        jButtonPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaActionPerformed(evt);
            }
        });

        jTablePretraga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePretraga.setViewportView(jTablePretraga);

        jButtonTreninzi.setText("Svi treninzi člana");
        jButtonTreninzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreninziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrikazLayout = new javax.swing.GroupLayout(jPanelPrikaz);
        jPanelPrikaz.setLayout(jPanelPrikazLayout);
        jPanelPrikazLayout.setHorizontalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePretraga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jButtonPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrikazLayout.createSequentialGroup()
                        .addComponent(jLabelPretraga)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonTreninzi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrikazLayout.setVerticalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPretraga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTreninzi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaActionPerformed
        pretrazi();
    }//GEN-LAST:event_jButtonPretragaActionPerformed

    private void jButtonTreninziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreninziActionPerformed
       popuniTabelu();
    }//GEN-LAST:event_jButtonTreninziActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonPretraga;
    private javax.swing.JButton jButtonTreninzi;
    private com.toedter.calendar.JDateChooser jDateChooserPretraga;
    private javax.swing.JLabel jLabelPretraga;
    private javax.swing.JPanel jPanelPrikaz;
    private javax.swing.JScrollPane jScrollPanePretraga;
    private javax.swing.JTable jTablePretraga;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        ServerskiOdgovor so = Kontroler.getInstance().vratiListuTreninga();
        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikaz = new ArrayList<>();

        for (Trening trening : listaTreninga) {
            if (ulogovanClan.getGrupa().getGrupaID().equals(trening.getGrupa().getGrupaID())) {
                prikaz.add(trening);
            }
        }

        TableModelTrening tmt = new TableModelTrening(prikaz);
        jTablePretraga.setModel(tmt);
    }

    public void pretrazi() {
        Date datum = jDateChooserPretraga.getDate();
        ServerskiOdgovor so = Kontroler.getInstance().pretraziTreninge();
        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikaz = new ArrayList<>();

        for (Trening trening : listaTreninga) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                Date da = trening.getDatumVreme();
                String dat = sdf.format(da);
                Date datu = sdf.parse(dat);

                if (ulogovanClan.getGrupa().getGrupaID().equals(trening.getGrupa().getGrupaID())) {
                    if (datu.equals(datum)) {
                        prikaz.add(trening);
                    }
                }

            } catch (ParseException ex) {
                Logger.getLogger(FrmPrikazTreningaClan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Greška sa formatom datuma!!");
            }
        }
        
        TableModelTrening tmt = (TableModelTrening) jTablePretraga.getModel();
        tmt.setListaTreninga(prikaz);
    }
}
