/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.trening;

import domen.Prisustvo;
import domen.Trener;
import domen.Trening;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.TableModelPrisustvo;
import model.TableModelTreningEvidencija;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrikazTreningaTrenerSaPrisustvom extends javax.swing.JDialog {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    public void setUlogovanTrener(Trener ulogovanTrener) {
        this.ulogovanTrener = ulogovanTrener;
    }

    public Trener getUlogovanTrener() {
        return ulogovanTrener;
    }

    /**
     * Creates new form FrmPrikazTreningaTrenerSaPrisustvom
     */
    public FrmPrikazTreningaTrenerSaPrisustvom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        popuniTreninge();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrikaz = new javax.swing.JPanel();
        jPanelPrisustva = new javax.swing.JPanel();
        jScrollPanePrisustvo = new javax.swing.JScrollPane();
        jTablePrisustvo = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jPanelIzaberiTrening = new javax.swing.JPanel();
        jScrollPaneTrening = new javax.swing.JScrollPane();
        jTableTrening = new javax.swing.JTable();
        jButtonPretragaPrisustva = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz treninga sa prisustvom");

        jPanelPrikaz.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaz treninga"));

        jPanelPrisustva.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaži prisustva člana"));
        jPanelPrisustva.setToolTipText("");

        jTablePrisustvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePrisustvo.setViewportView(jTablePrisustvo);

        jButtonObrisi.setText("Obriši prisustvo");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrisustvaLayout = new javax.swing.GroupLayout(jPanelPrisustva);
        jPanelPrisustva.setLayout(jPanelPrisustvaLayout);
        jPanelPrisustvaLayout.setHorizontalGroup(
            jPanelPrisustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrisustvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrisustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePrisustvo)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrisustvaLayout.setVerticalGroup(
            jPanelPrisustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrisustvaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanePrisustvo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonObrisi)
                .addContainerGap())
        );

        jPanelIzaberiTrening.setBorder(javax.swing.BorderFactory.createTitledBorder("Izaberi trening"));

        jTableTrening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTrening.setViewportView(jTableTrening);

        jButtonPretragaPrisustva.setText("Prikaži prisustva za odabrani trening");
        jButtonPretragaPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaPrisustvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIzaberiTreningLayout = new javax.swing.GroupLayout(jPanelIzaberiTrening);
        jPanelIzaberiTrening.setLayout(jPanelIzaberiTreningLayout);
        jPanelIzaberiTreningLayout.setHorizontalGroup(
            jPanelIzaberiTreningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzaberiTreningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIzaberiTreningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTrening, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addComponent(jButtonPretragaPrisustva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelIzaberiTreningLayout.setVerticalGroup(
            jPanelIzaberiTreningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzaberiTreningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPretragaPrisustva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrikazLayout = new javax.swing.GroupLayout(jPanelPrikaz);
        jPanelPrikaz.setLayout(jPanelPrikazLayout);
        jPanelPrikazLayout.setHorizontalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIzaberiTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrisustva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrikazLayout.setVerticalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIzaberiTrening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPrisustva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonPretragaPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaPrisustvaActionPerformed

        Trening trening;

        int red = jTableTrening.getSelectedRow();

        if (red != -1) {
            TableModelTreningEvidencija tmte = (TableModelTreningEvidencija) jTableTrening.getModel();
            trening = tmte.uzmiTrening(red);
        } else {
            JOptionPane.showMessageDialog(this, "Odaberite trening za koji želite prikaz prisustva!!");
            return;
        }

        ServerskiOdgovor so = Kontroler.getInstance().pretraziPrisustva();
        ArrayList<Prisustvo> listaPrisustva = (ArrayList<Prisustvo>) so.getOdgovor();
        ArrayList<Prisustvo> prikaz = new ArrayList<>();

        for (Prisustvo prisustvo : listaPrisustva) {

            if (ulogovanTrener.getTrenerID().equals(prisustvo.getTrening().getTrener().getTrenerID())) {
                if (trening.getDatumVreme().equals(prisustvo.getTrening().getDatumVreme())) {
                    prikaz.add(prisustvo);
                }
            }
        }

        TableModelPrisustvo tmp = new TableModelPrisustvo(prikaz);
        jTablePrisustvo.setModel(tmp);


    }//GEN-LAST:event_jButtonPretragaPrisustvaActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
          int red = jTablePrisustvo.getSelectedRow();

        if (red != -1) {

            TableModelPrisustvo tmc = (TableModelPrisustvo) jTablePrisustvo.getModel();

            Prisustvo prisustvo = tmc.uzmiPrisustvo(red);

            if (ulogovanTrener.getTrenerID().equals(prisustvo.getTrening().getTrener().getTrenerID())) {

                Long prisusustvoID = (Long) jTablePrisustvo.getValueAt(red, 0);
                
                tmc.obrisiPrisustvo(red);

                Prisustvo obrisano= new Prisustvo();
                obrisano.setPrisustvoID(prisusustvoID);
                
                ServerskiOdgovor so = Kontroler.getInstance().obrisiPrisustvo(obrisano);
                so.getPoruka();

                if (so.isUspesnost()) {
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao izabrano prisustvo!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem nije obrisao izabrano prisustvo!!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Trener može obrisati samo prisustva svojih članova!!");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Odaberite prisustvo koje želite da obrišete!!");
            return;
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPretragaPrisustva;
    private javax.swing.JPanel jPanelIzaberiTrening;
    private javax.swing.JPanel jPanelPrikaz;
    private javax.swing.JPanel jPanelPrisustva;
    private javax.swing.JScrollPane jScrollPanePrisustvo;
    private javax.swing.JScrollPane jScrollPaneTrening;
    private javax.swing.JTable jTablePrisustvo;
    private javax.swing.JTable jTableTrening;
    // End of variables declaration//GEN-END:variables

    private void popuniTreninge() {
        ServerskiOdgovor so = Kontroler.getInstance().pretraziTreninge();

        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikazT = new ArrayList<>();

        for (Trening trening : listaTreninga) {
            if (ulogovanTrener.getTrenerID().equals(trening.getTrener().getTrenerID())) {
                prikazT.add(trening);
            }
        }

        TableModelTreningEvidencija tmte = new TableModelTreningEvidencija(prikazT);
        jTableTrening.setModel(tmte);
    }
}
