/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.trening;

import domen.Grupa;
import domen.Trener;
import domen.Trening;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import kontroler.Kontroler;
import model.TableModelTrening;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrikazTreningaTrener extends javax.swing.JDialog {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    /**
     * Creates new form FrmPrikazTreningaTrener
     */
    public FrmPrikazTreningaTrener(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        popuniComboGrupa();

        popuniTabelu();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrikaz = new javax.swing.JPanel();
        jDateChooserPretraga = new com.toedter.calendar.JDateChooser();
        jLabelPretraga = new javax.swing.JLabel();
        jButtonPretraga = new javax.swing.JButton();
        jScrollPanePretraga = new javax.swing.JScrollPane();
        jTablePretraga = new javax.swing.JTable();
        jButtonTreninzi = new javax.swing.JButton();
        jLabelPretragaGrupa = new javax.swing.JLabel();
        jComboBoxGrupa = new javax.swing.JComboBox<>();
        jButtonPretragaGrupa = new javax.swing.JButton();
        jButtonPrisustvaTrening = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jLabelPoruka = new javax.swing.JLabel();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz treninga - trener");

        jPanelPrikaz.setBorder(javax.swing.BorderFactory.createTitledBorder("Prikaz treninga - trener"));

        jLabelPretraga.setText("Pretraži trening po datumu: ");

        jButtonPretraga.setText("Pretraga po datumu");
        jButtonPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaActionPerformed(evt);
            }
        });

        jTablePretraga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePretraga.setViewportView(jTablePretraga);

        jButtonTreninzi.setText("Svi treninzi trenera");
        jButtonTreninzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreninziActionPerformed(evt);
            }
        });

        jLabelPretragaGrupa.setText("Pretraži trening po grupi: ");

        jComboBoxGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPretragaGrupa.setText("Pretraga po grupi");
        jButtonPretragaGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretragaGrupaActionPerformed(evt);
            }
        });

        jButtonPrisustvaTrening.setText("Detaljan prikaz treninga i prisustva");
        jButtonPrisustvaTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrisustvaTreningActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši trening");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabelPoruka.setText("Možete obrisati trening samo ukoliko ne postoje evidentirana prisustva za isti!");

        javax.swing.GroupLayout jPanelPrikazLayout = new javax.swing.GroupLayout(jPanelPrikaz);
        jPanelPrikaz.setLayout(jPanelPrikazLayout);
        jPanelPrikazLayout.setHorizontalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePretraga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTreninzi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrikazLayout.createSequentialGroup()
                        .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                                .addComponent(jLabelPretraga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addComponent(jButtonPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPretragaGrupa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrikazLayout.createSequentialGroup()
                                .addComponent(jLabelPretragaGrupa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrikazLayout.createSequentialGroup()
                        .addComponent(jButtonPrisustvaTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelPrikazLayout.setVerticalGroup(
            jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrikazLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPretraga)
                    .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPretragaGrupa)
                        .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPretraga)
                    .addComponent(jButtonPretragaGrupa))
                .addGap(18, 18, 18)
                .addComponent(jButtonTreninzi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrikazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrisustvaTrening)
                    .addComponent(jButtonObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPoruka)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaActionPerformed
        pretrazi();
    }//GEN-LAST:event_jButtonPretragaActionPerformed

    private void jButtonTreninziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreninziActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jButtonTreninziActionPerformed

    private void jButtonPretragaGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretragaGrupaActionPerformed
        pretraziPoGrupi();
    }//GEN-LAST:event_jButtonPretragaGrupaActionPerformed

    private void jButtonPrisustvaTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrisustvaTreningActionPerformed
        FrmPrikazTreningaTrenerSaPrisustvom formaPrikazTreningaSaPrisustvom = new FrmPrikazTreningaTrenerSaPrisustvom(null, true);
        formaPrikazTreningaSaPrisustvom.pack();
        formaPrikazTreningaSaPrisustvom.setVisible(true);
    }//GEN-LAST:event_jButtonPrisustvaTreningActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int red = jTablePretraga.getSelectedRow();

        if (red != -1) {

            TableModelTrening tmt = (TableModelTrening) jTablePretraga.getModel();

            Trening trening = tmt.uzmiTrening(red);

            if (ulogovanTrener.getTrenerID().equals(trening.getTrener().getTrenerID())) {

                Long treningID = (Long) jTablePretraga.getValueAt(red, 0);
                
                tmt.obrisiTrening(red);

                Trening obrisan= new Trening();
                obrisan.setTreningID(treningID);
                
                ServerskiOdgovor so = Kontroler.getInstance().obrisiTrening(obrisan);
                so.getPoruka();

                if (so.isUspesnost()) {
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao izabrani trening!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem nije obrisao izabrani trening!!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Trener može obrisati samo treninge svojih članova!!");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Odaberite trening koji želite da obrišete!!");
            return;
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPretraga;
    private javax.swing.JButton jButtonPretragaGrupa;
    private javax.swing.JButton jButtonPrisustvaTrening;
    private javax.swing.JButton jButtonTreninzi;
    private javax.swing.JComboBox<Object> jComboBoxGrupa;
    private com.toedter.calendar.JDateChooser jDateChooserPretraga;
    private javax.swing.JLabel jLabelPoruka;
    private javax.swing.JLabel jLabelPretraga;
    private javax.swing.JLabel jLabelPretragaGrupa;
    private javax.swing.JPanel jPanelPrikaz;
    private javax.swing.JScrollPane jScrollPanePretraga;
    private javax.swing.JTable jTablePretraga;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        ServerskiOdgovor so = Kontroler.getInstance().vratiListuTreninga();
        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikaz = new ArrayList<>();

        for (Trening trening : listaTreninga) {
            if (ulogovanTrener.getTrenerID().equals(trening.getTrener().getTrenerID())) {
                prikaz.add(trening);
            }
        }

        TableModelTrening tmt = new TableModelTrening(prikaz);
        jTablePretraga.setModel(tmt);
    }

    private void pretrazi() {
        Date datum = jDateChooserPretraga.getDate();
        ServerskiOdgovor so = Kontroler.getInstance().pretraziTreninge();
        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikaz = new ArrayList<>();

        for (Trening trening : listaTreninga) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                Date da = trening.getDatumVreme();
                String dat = sdf.format(da);
                Date datu = sdf.parse(dat);

                if (ulogovanTrener.getTrenerID().equals(trening.getTrener().getTrenerID())) {
                    if (datu.equals(datum)) {
                        prikaz.add(trening);
                    }
                }

            } catch (ParseException ex) {
                Logger.getLogger(FrmPrikazTreningaClan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Greška sa formatom datuma!!");
            }
        }

        TableModelTrening tmt = (TableModelTrening) jTablePretraga.getModel();
        tmt.setListaTreninga(prikaz);
    }

    private void popuniComboGrupa() {
        jComboBoxGrupa.removeAllItems(); //uklanjanje default vrednosti

        ServerskiOdgovor so = Kontroler.getInstance().vratiListuGrupa();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();

        for (Grupa g : listaGrupa) {

            if (g.getTrener().getTrenerID().equals(ulogovanTrener.getTrenerID())) {
                jComboBoxGrupa.addItem(g);
            }

        }

    }

    private void pretraziPoGrupi() {

        Grupa grupa = (Grupa) jComboBoxGrupa.getSelectedItem();
        
         if(grupa == null){
            JOptionPane.showMessageDialog(this, "Trener ne trenira nijednu grupu!! Napravi novu grupu!!");
            return;
        }
        ServerskiOdgovor so = Kontroler.getInstance().pretraziTreninge();
        ArrayList<Trening> listaTreninga = (ArrayList<Trening>) so.getOdgovor();
        ArrayList<Trening> prikaz = new ArrayList<>();

        for (Trening trening : listaTreninga) {

            if (ulogovanTrener.getTrenerID().equals(trening.getTrener().getTrenerID())) {
                if(grupa.getGrupaID().equals(trening.getGrupa().getGrupaID())){
                prikaz.add(trening);
                }
            }

        }

        TableModelTrening tmt = (TableModelTrening) jTablePretraga.getModel();
        tmt.setListaTreninga(prikaz);
    }

    Trening uzmiTrening() {
        
        int red = jTablePretraga.getSelectedRow();
        Trening trening;
        if(red != -1){
        
        TableModelTrening tmt = (TableModelTrening) jTablePretraga.getModel();
        trening = tmt.uzmiTrening(red);
        
    } else{
            JOptionPane.showMessageDialog(this, "Nije izabran nijedan trening! Izabreri trening za koji želiš uvid u prisustva!!");
            trening = null;
        }
        return trening;
    }
}
