/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.trening;

import domen.Grupa;
import domen.Trener;
import domen.Trening;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmUnosTreninga extends javax.swing.JDialog {

    private Trener ulogovanTrener = sesija.Sesija.getInstance().getTrener();

    public Trener getUlogovanTrener() {
        return ulogovanTrener;
    }

    public void setUlogovanTrener(Trener ulogovanTrener) {
        this.ulogovanTrener = ulogovanTrener;
    }

    /**
     * Creates new form FrmUnosTreninga
     */
    public FrmUnosTreninga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        popuniComboBox();
        jLabelTrenerPrikaz.setText(ulogovanTrener + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUnos = new javax.swing.JPanel();
        jTextFieldDatum = new javax.swing.JTextField();
        jScrollPaneOpis = new javax.swing.JScrollPane();
        jTextAreaOpis = new javax.swing.JTextArea();
        jLabelTrenerPrikaz = new javax.swing.JLabel();
        jComboBoxGrupa = new javax.swing.JComboBox<>();
        jButtonUnos = new javax.swing.JButton();
        jLabelFormat = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jLabelOpis = new javax.swing.JLabel();
        jLabelTrener = new javax.swing.JLabel();
        jLabelGrupa = new javax.swing.JLabel();
        jLabelOpisOpciono = new javax.swing.JLabel();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos treninga");

        jPanelUnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos treninga"));

        jTextAreaOpis.setColumns(20);
        jTextAreaOpis.setRows(5);
        jScrollPaneOpis.setViewportView(jTextAreaOpis);

        jLabelTrenerPrikaz.setText("Ime trenera");

        jComboBoxGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrupaActionPerformed(evt);
            }
        });

        jButtonUnos.setText("Sačuvaj novi trening");
        jButtonUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnosActionPerformed(evt);
            }
        });

        jLabelFormat.setText("(dd.MM.yyyy HH:mm)");

        jLabelDatum.setText("Datum i vreme: ");

        jLabelOpis.setText("Opis treninga: ");

        jLabelTrener.setText("Trener: ");

        jLabelGrupa.setText("Grupa: ");

        jLabelOpisOpciono.setText("(opciono)");

        javax.swing.GroupLayout jPanelUnosLayout = new javax.swing.GroupLayout(jPanelUnos);
        jPanelUnos.setLayout(jPanelUnosLayout);
        jPanelUnosLayout.setHorizontalGroup(
            jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                        .addComponent(jLabelDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDatum))
                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpis)
                            .addComponent(jLabelTrener)
                            .addComponent(jLabelGrupa)
                            .addComponent(jLabelOpisOpciono))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUnosLayout.createSequentialGroup()
                                .addComponent(jLabelFormat)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelTrenerPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneOpis, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                            .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelUnosLayout.setVerticalGroup(
            jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatum)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                        .addComponent(jLabelOpis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOpisOpciono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrenerPrikaz)
                    .addComponent(jLabelTrener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGrupa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonUnos)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addComponent(jButtonNazad)
                .addContainerGap())
            .addComponent(jPanelUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnosActionPerformed
        String dat = jTextFieldDatum.getText();
        String opis = jTextAreaOpis.getText();
        
        if(dat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti polje za datum treninga!!");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        try {
            Date datumVreme = sdf.parse(dat);
            
            if(datumVreme.before(new Date())){
                JOptionPane.showMessageDialog(this, "Novi trening je moguće kreirati za današnji datum ili naredni period!!");
                return;
            }
            
            Grupa grupa = (Grupa) jComboBoxGrupa.getSelectedItem();
            Trener trener = ulogovanTrener;
            
            if(grupa == null){
                JOptionPane.showMessageDialog(this, "Trener ne trenira nijednu grupu, prvo kreirajte novu grupu!!");
                return;
            }
            
            Trening trening = new Trening(-1L, datumVreme, opis, trener, grupa);
            ServerskiOdgovor so = Kontroler.getInstance().zapamtiTrening(trening);
            JOptionPane.showMessageDialog(this, so.getPoruka());
            
            boolean uspesnost = so.isUspesnost();
            if(uspesnost){
                 JOptionPane.showMessageDialog(this, "Sistem je uspešno sačuvao novi trening!!");
            }else{
                 JOptionPane.showMessageDialog(this, "Neuspešno čuvanje novog treninga!!");
            }
            
            resetPolja();
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Pogrešan format datuma!!");
            Logger.getLogger(FrmUnosTreninga.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        
    }//GEN-LAST:event_jButtonUnosActionPerformed

    private void jComboBoxGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGrupaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonUnos;
    private javax.swing.JComboBox<Object> jComboBoxGrupa;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelGrupa;
    private javax.swing.JLabel jLabelOpis;
    private javax.swing.JLabel jLabelOpisOpciono;
    private javax.swing.JLabel jLabelTrener;
    private javax.swing.JLabel jLabelTrenerPrikaz;
    private javax.swing.JPanel jPanelUnos;
    private javax.swing.JScrollPane jScrollPaneOpis;
    private javax.swing.JTextArea jTextAreaOpis;
    private javax.swing.JTextField jTextFieldDatum;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        jComboBoxGrupa.removeAllItems(); //uklanjanje default vrednosti

        ServerskiOdgovor so = Kontroler.getInstance().vratiListuGrupa();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();

        for (Grupa g : listaGrupa) {
            if(g.getTrener().getTrenerID().equals(ulogovanTrener.getTrenerID())){
            jComboBoxGrupa.addItem(g);
            }
            
        }

    }

    private void resetPolja() {
       jTextFieldDatum.setText("");
       jTextAreaOpis.setText("");
    }
    
}
