/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.clan;

import domen.Clan;
import domen.Grupa;
import domen.Trener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmUnosClana extends javax.swing.JDialog {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    public void setUlogovanTrener(Trener ulogovanTrener) {
        this.ulogovanTrener = ulogovanTrener;
    }

    public Trener getUlogovanTrener() {
        return ulogovanTrener;
    }
    
    /**
     * Creates new form FrmUnosClana
     */
    public FrmUnosClana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUnos = new javax.swing.JPanel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jDateChooserDatum = new com.toedter.calendar.JDateChooser();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxGrupa = new javax.swing.JComboBox<>();
        jButtonUnos = new javax.swing.JButton();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelGrupa = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos člana");

        jPanelUnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos člana"));

        jDateChooserDatum.setDateFormatString("dd.MM.yyyy");

        jComboBoxGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonUnos.setText("Sačuvaj novog člana");
        jButtonUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnosActionPerformed(evt);
            }
        });

        jLabelIme.setText("Ime: ");

        jLabelPrezime.setText("Prezime: ");

        jLabelDatum.setText("Datum rođenja: ");

        jLabelTelefon.setText("Telefon: ");

        jLabelEmail.setText("E-mail: ");

        jLabelPass.setText("Password: ");

        jLabelGrupa.setText("Grupa: ");

        javax.swing.GroupLayout jPanelUnosLayout = new javax.swing.GroupLayout(jPanelUnos);
        jPanelUnos.setLayout(jPanelUnosLayout);
        jPanelUnosLayout.setHorizontalGroup(
            jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIme, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefon)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIme)
                            .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldPass))))
                .addContainerGap())
        );
        jPanelUnosLayout.setVerticalGroup(
            jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelUnosLayout.createSequentialGroup()
                                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelUnosLayout.createSequentialGroup()
                                                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanelUnosLayout.createSequentialGroup()
                                                        .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabelIme))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabelPrezime))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jDateChooserDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelDatum))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelTelefon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelEmail))
                        .addGap(30, 30, 30))
                    .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPass)
                        .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanelUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGrupa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButtonUnos)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnosActionPerformed
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        Date datumRodjenja = jDateChooserDatum.getDate();
        String telefon = jTextFieldTelefon.getText();
        String email = jTextFieldEmail.getText();
        char[] nizPass = jPasswordFieldPass.getPassword(); //Sifra je data kao niz (osetljiv podatak), moramo da je pretvorimo u string
        String pass = String.copyValueOf(nizPass); //Sad nam je sifra string
        Grupa grupa = (Grupa) jComboBoxGrupa.getSelectedItem();
        
        Date datum = null;

        try {
            String dat = "31.12.2003";
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            datum = sdf.parse(dat);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Greška u formatu datuma!", "Greška prilikom unosa novog člana", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmUnosClana.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (datumRodjenja.after(datumRodjenja)) {
            JOptionPane.showMessageDialog(this, "Članovi kluba moraju biti 2003. godište ili stariji!!", "Greška prilikom unosa novog člana", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         if (nizPass.length < 4) {
            JOptionPane.showMessageDialog(this, "Šifra mora imati najmanje 4 karaktera!", "Greška prilikom unosa novog člana", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
         if(telefon.length() < 9 || telefon.length() > 10){
             JOptionPane.showMessageDialog(this, "Unesite broj telefona u formatu 06X XXXX XXX ili 06X XXX XXX !!", "Greška prilikom unosa novog člana", JOptionPane.ERROR_MESSAGE);
                return;
         }
        
        
        if(grupa == null){
            JOptionPane.showMessageDialog(this, "Trener ne trenira nijednu grupu!! Napravi novu grupu!!");
            return;
        }
        
        int brojClanovaGrupe = grupa.getBrojClanova()+1;
        
        if(ime.isEmpty() || prezime.isEmpty() || datumRodjenja == null || telefon.isEmpty() || email.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!!");
            return;
        }
        
        if (!email.endsWith("@kbk.com")) {
            JOptionPane.showMessageDialog(this, "E-mail adresa se mora završavati sa @kbk.com", "Greška prilikom unosa novog člana", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(brojClanovaGrupe > grupa.getKapacitet()){
            JOptionPane.showMessageDialog(this, "Popunjen je kapacitet grupe, izaberite drugu!!");
            return;
        }
        
        Clan clan = new Clan(-1L, ime, prezime, datumRodjenja, telefon, email, pass, grupa);
        ServerskiOdgovor so = Kontroler.getInstance().zapamtiClana(clan);
        
        boolean sacuvan = so.isUspesnost();
        
        if(sacuvan){
            JOptionPane.showMessageDialog(this, "Sačuvan je novi član kluba!!");
            grupa.setBrojClanova(brojClanovaGrupe);
            ServerskiOdgovor so1 = Kontroler.getInstance().izmeniGrupu(grupa); //update broja clanova - dodat je novi
            
            reset();
        }else{
            JOptionPane.showMessageDialog(this, "Greška, sistem nije sačuvao novog člana kluba!!");
        }
    }//GEN-LAST:event_jButtonUnosActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonUnos;
    private javax.swing.JComboBox<Object> jComboBoxGrupa;
    private com.toedter.calendar.JDateChooser jDateChooserDatum;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGrupa;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JPanel jPanelUnos;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        jComboBoxGrupa.removeAllItems(); //uklanjanje default vrednosti

        ServerskiOdgovor so = Kontroler.getInstance().vratiListuGrupa();
        ArrayList<Grupa> listaGrupa = (ArrayList<Grupa>) so.getOdgovor();

        for (Grupa g : listaGrupa) {
           
            if(g.getTrener().getTrenerID().equals(ulogovanTrener.getTrenerID())){
            jComboBoxGrupa.addItem(g);
            }
        }
    }

    private void reset() {
       jTextFieldIme.setText("");
       jTextFieldPrezime.setText("");
       jTextFieldTelefon.setText("");
       jTextFieldEmail.setText("");
       jPasswordFieldPass.setText("");
       jDateChooserDatum.setDate(null);
    }
}
