/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Clan;
import forma.clan.FrmIzmenaPodatakaClana;
import forma.trening.FrmPrikazTreningaClan;
import sesija.SesijaClan;

/**
 *
 * @author Natasa
 */
public class FrmGlavnaClan extends javax.swing.JFrame {
private Clan ulogovanClan = SesijaClan.getInstance().getClan();
Clan trenutnoUlogovan;

    public void setTrenutnoUlogovan(Clan trenutnoUlogovan) {
        this.trenutnoUlogovan = trenutnoUlogovan;
        jLabelTrenutniClan.setText("Dobro došli, "+trenutnoUlogovan);
        jLabelNazivGrupe.setText(trenutnoUlogovan.getGrupa().getNaziv()+"");
        System.out.println(trenutnoUlogovan);
    }

    public Clan getTrenutnoUlogovan() {
        return trenutnoUlogovan;
    }


    /**
     * Creates new form FrmGlavnaClan
     */
    public FrmGlavnaClan() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGlavna = new javax.swing.JPanel();
        jLabelIzmena = new javax.swing.JLabel();
        jButtonIzmena = new javax.swing.JButton();
        jLabelPregled = new javax.swing.JLabel();
        jButtonPregled = new javax.swing.JButton();
        jButtonOdjava = new javax.swing.JButton();
        jLabelTrenutniClan = new javax.swing.JLabel();
        jLabelGrupa = new javax.swing.JLabel();
        jLabelNazivGrupe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna - član");

        jPanelGlavna.setBorder(javax.swing.BorderFactory.createTitledBorder("Glavna forma - član"));

        jLabelIzmena.setText("Izmena ličnih podataka: ");

        jButtonIzmena.setText("Izmena podataka");
        jButtonIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmenaActionPerformed(evt);
            }
        });

        jLabelPregled.setText("Uvid u treninge: ");

        jButtonPregled.setText("Pregled treninga");
        jButtonPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledActionPerformed(evt);
            }
        });

        jButtonOdjava.setText("Odjavi se");
        jButtonOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjavaActionPerformed(evt);
            }
        });

        jLabelTrenutniClan.setText("Trenutni član");

        jLabelGrupa.setText("Grupa:");

        jLabelNazivGrupe.setText("Naziv grupe");

        javax.swing.GroupLayout jPanelGlavnaLayout = new javax.swing.GroupLayout(jPanelGlavna);
        jPanelGlavna.setLayout(jPanelGlavnaLayout);
        jPanelGlavnaLayout.setHorizontalGroup(
            jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlavnaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOdjava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGlavnaLayout.createSequentialGroup()
                        .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrenutniClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelGlavnaLayout.createSequentialGroup()
                                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIzmena)
                                    .addComponent(jLabelPregled)
                                    .addComponent(jLabelGrupa))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIzmena, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                                    .addGroup(jPanelGlavnaLayout.createSequentialGroup()
                                        .addComponent(jLabelNazivGrupe)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanelGlavnaLayout.setVerticalGroup(
            jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlavnaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTrenutniClan)
                .addGap(20, 20, 20)
                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIzmena)
                    .addComponent(jButtonIzmena))
                .addGap(18, 18, 18)
                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPregled)
                    .addComponent(jLabelPregled))
                .addGap(18, 18, 18)
                .addGroup(jPanelGlavnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrupa)
                    .addComponent(jLabelNazivGrupe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonOdjava)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGlavna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGlavna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjavaActionPerformed
        FrmPocetna formaPocetna = new FrmPocetna();
        formaPocetna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOdjavaActionPerformed

    private void jButtonPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledActionPerformed
        FrmPrikazTreningaClan formaPrikaz = new FrmPrikazTreningaClan(this, true);
        formaPrikaz.pack();
        formaPrikaz.setVisible(true);
    }//GEN-LAST:event_jButtonPregledActionPerformed

    private void jButtonIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmenaActionPerformed
        FrmIzmenaPodatakaClana formaIzmena = new FrmIzmenaPodatakaClana(this, true);
        formaIzmena.pack();
        formaIzmena.setUlogovanClan(ulogovanClan);
        formaIzmena.setVisible(true);
    }//GEN-LAST:event_jButtonIzmenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmena;
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JButton jButtonPregled;
    private javax.swing.JLabel jLabelGrupa;
    private javax.swing.JLabel jLabelIzmena;
    private javax.swing.JLabel jLabelNazivGrupe;
    private javax.swing.JLabel jLabelPregled;
    private javax.swing.JLabel jLabelTrenutniClan;
    private javax.swing.JPanel jPanelGlavna;
    // End of variables declaration//GEN-END:variables
}
