/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Trener;
import forma.clan.FrmPrikazIBrisanjeClana;
import forma.clan.FrmUnosClana;
import forma.grupa.FrmDodajGrupu;
import forma.grupa.FrmPrikazGrupe;
import forma.prisustvo.FrmEvidencijaPrisustva;
import forma.prisustvo.FrmPregledPrisustva;
import forma.trener.FrmIzmenaPodatakaTrener;
import forma.trening.FrmPrikazTreningaTrener;
import forma.trening.FrmUnosTreninga;
import javax.swing.JFrame;
import sesija.Sesija;

/**
 *
 * @author Natasa
 */
public class FrmGlavnaTrener extends javax.swing.JFrame {

    private Trener ulogovanTrener = Sesija.getInstance().getTrener();
    Trener trenutnoUlogovan;

    public Trener getTrenutnoUlogovan() {
        return trenutnoUlogovan;
    }

    public void setTrenutnoUlogovan(Trener trenutnoUlogovan) {
        this.trenutnoUlogovan = trenutnoUlogovan;
        jLabelTrenutniTrener.setText("Dobro došli, "+trenutnoUlogovan);
        System.out.println(trenutnoUlogovan);
    }
    
    
    /**
     * Creates new form FrmGlavnaTrener
     */
    public FrmGlavnaTrener() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOdjava = new javax.swing.JButton();
        jLabelTrenutniTrener = new javax.swing.JLabel();
        jLabelPoruka = new javax.swing.JLabel();
        jMenuBarMeni = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemUnosClana = new javax.swing.JMenuItem();
        jMenuItemBrisanjeClana = new javax.swing.JMenuItem();
        jMenuItemUnosGrupe = new javax.swing.JMenuItem();
        jMenuItemPrikazGrupe = new javax.swing.JMenuItem();
        jMenuItemUnosTreninga = new javax.swing.JMenuItem();
        jMenuItemPregledTreninga = new javax.swing.JMenuItem();
        jMenuItemUnosPrisustva = new javax.swing.JMenuItem();
        jMenuItemPregledPrisustva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna - trener");

        jButtonOdjava.setText("Odjavi se");
        jButtonOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjavaActionPerformed(evt);
            }
        });

        jLabelTrenutniTrener.setText("Trenutni trener");

        jLabelPoruka.setText("Klikom na meni odaberite radnju koju želite da izvršite!");

        jMenu1.setText("Meni");

        jMenuItem1.setText("Izmeni podatke o treneru");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItemUnosClana.setText("Unos novog člana");
        jMenuItemUnosClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosClanaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosClana);

        jMenuItemBrisanjeClana.setText("Pregled i brisanje članova");
        jMenuItemBrisanjeClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBrisanjeClanaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBrisanjeClana);

        jMenuItemUnosGrupe.setText("Unos nove grupe");
        jMenuItemUnosGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosGrupeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosGrupe);

        jMenuItemPrikazGrupe.setText("Pregled i brisanje grupa");
        jMenuItemPrikazGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazGrupeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPrikazGrupe);

        jMenuItemUnosTreninga.setText("Unos treninga");
        jMenuItemUnosTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosTreningaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosTreninga);

        jMenuItemPregledTreninga.setText("Pregled i brisanje treninga");
        jMenuItemPregledTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledTreningaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledTreninga);

        jMenuItemUnosPrisustva.setText("Unos prisustva");
        jMenuItemUnosPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosPrisustvaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosPrisustva);

        jMenuItemPregledPrisustva.setText("Pregled i brisanje prisustva");
        jMenuItemPregledPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledPrisustvaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledPrisustva);

        jMenuBarMeni.add(jMenu1);

        setJMenuBar(jMenuBarMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 622, Short.MAX_VALUE)
                        .addComponent(jButtonOdjava))
                    .addComponent(jLabelTrenutniTrener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTrenutniTrener)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPoruka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jButtonOdjava)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjavaActionPerformed
        FrmPocetna formaPocetna = new FrmPocetna();
        formaPocetna.setVisible(true);
        this.dispose();
        setTrenutnoUlogovan(null);
    }//GEN-LAST:event_jButtonOdjavaActionPerformed

    private void jMenuItemUnosClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosClanaActionPerformed
        FrmUnosClana formaUnos = new FrmUnosClana(this, true);
        formaUnos.pack();
        formaUnos.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosClanaActionPerformed

    private void jMenuItemBrisanjeClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBrisanjeClanaActionPerformed
        FrmPrikazIBrisanjeClana formaBrisanje = new FrmPrikazIBrisanjeClana(this, true);
        formaBrisanje.pack();
        formaBrisanje.setVisible(true);
    }//GEN-LAST:event_jMenuItemBrisanjeClanaActionPerformed

    private void jMenuItemPrikazGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazGrupeActionPerformed
        FrmPrikazGrupe formaPrikazGrupe = new FrmPrikazGrupe(this, true);
        formaPrikazGrupe.pack();
        formaPrikazGrupe.setUlogovanTrener(trenutnoUlogovan);
        formaPrikazGrupe.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikazGrupeActionPerformed

    private void jMenuItemUnosTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosTreningaActionPerformed
        FrmUnosTreninga formaUnosTreninga = new FrmUnosTreninga(this, true);
        Trener ulogovan = getTrenutnoUlogovan();
        formaUnosTreninga.pack();
        formaUnosTreninga.setUlogovanTrener(ulogovan);
        formaUnosTreninga.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosTreningaActionPerformed

    private void jMenuItemPregledTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledTreningaActionPerformed
        FrmPrikazTreningaTrener formaPrikazTreninga = new FrmPrikazTreningaTrener(this, true);
        formaPrikazTreninga.pack();
        formaPrikazTreninga.setVisible(true);
    }//GEN-LAST:event_jMenuItemPregledTreningaActionPerformed

    private void jMenuItemUnosPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosPrisustvaActionPerformed
        FrmEvidencijaPrisustva formaUnosPrisustva = new FrmEvidencijaPrisustva(this, true);
        formaUnosPrisustva.pack();
        formaUnosPrisustva.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosPrisustvaActionPerformed

    private void jMenuItemPregledPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledPrisustvaActionPerformed
        FrmPregledPrisustva formaPregledPrisustva = new FrmPregledPrisustva(this, true);
        formaPregledPrisustva.pack();
        formaPregledPrisustva.setVisible(true);
    }//GEN-LAST:event_jMenuItemPregledPrisustvaActionPerformed

    private void jMenuItemUnosGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosGrupeActionPerformed
        FrmDodajGrupu formaDodajGrupu = new FrmDodajGrupu(this, true);
        formaDodajGrupu.pack();
        formaDodajGrupu.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosGrupeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FrmIzmenaPodatakaTrener formaIzmenaPodatakaTrener = new FrmIzmenaPodatakaTrener(this, true);
       formaIzmenaPodatakaTrener.pack();
       formaIzmenaPodatakaTrener.setUlogovanTrener(trenutnoUlogovan);
       formaIzmenaPodatakaTrener.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JLabel jLabelPoruka;
    private javax.swing.JLabel jLabelTrenutniTrener;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarMeni;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemBrisanjeClana;
    private javax.swing.JMenuItem jMenuItemPregledPrisustva;
    private javax.swing.JMenuItem jMenuItemPregledTreninga;
    private javax.swing.JMenuItem jMenuItemPrikazGrupe;
    private javax.swing.JMenuItem jMenuItemUnosClana;
    private javax.swing.JMenuItem jMenuItemUnosGrupe;
    private javax.swing.JMenuItem jMenuItemUnosPrisustva;
    private javax.swing.JMenuItem jMenuItemUnosTreninga;
    // End of variables declaration//GEN-END:variables

   
}
