/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forma;

import domen.Clan;
import domen.Grupa;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.SesijaClan;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrijavljivanjeClan extends javax.swing.JFrame {

    /** Creates new form FrmPrijavljivanjeClan */
    public FrmPrijavljivanjeClan() {
        initComponents();
        setLocationRelativeTo(null);
        
        jLabelPrikaziPass.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrijava = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonPrijava = new javax.swing.JButton();
        jLabelPrikaziPass = new javax.swing.JLabel();
        jButtonPrikaziPass = new javax.swing.JButton();
        jButtonPocetna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijavljivanje - član");

        jPanelPrijava.setBorder(javax.swing.BorderFactory.createTitledBorder("Prijavljivanje na sistem"));
        jPanelPrijava.setToolTipText("");

        jLabelEmail.setText("email: ");

        jLabelPass.setText("password: ");

        jPasswordFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassActionPerformed(evt);
            }
        });

        jButtonPrijava.setText("Prijavi se");
        jButtonPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrijavaActionPerformed(evt);
            }
        });

        jLabelPrikaziPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonPrikaziPass.setText("Prikaži password");
        jButtonPrikaziPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrijavaLayout = new javax.swing.GroupLayout(jPanelPrijava);
        jPanelPrijava.setLayout(jPanelPrijavaLayout);
        jPanelPrijavaLayout.setHorizontalGroup(
            jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                        .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                                .addComponent(jLabelPrikaziPass, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 327, Short.MAX_VALUE))
                            .addComponent(jPasswordFieldPass)
                            .addComponent(jTextFieldEmail)))
                    .addComponent(jButtonPrikaziPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrijava, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrijavaLayout.setVerticalGroup(
            jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrikaziPass, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButtonPrikaziPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPrijava)
                .addContainerGap())
        );

        jButtonPocetna.setText("Početna forma");
        jButtonPocetna.setAlignmentY(0.0F);
        jButtonPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPocetnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPocetna)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPocetna)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPocetnaActionPerformed
       FrmPocetna formaPocetna = new FrmPocetna();
       formaPocetna.pack();
       formaPocetna.setVisible(true); 
       this.dispose();
    }//GEN-LAST:event_jButtonPocetnaActionPerformed

    private void jButtonPrikaziPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPassActionPerformed
        char[] pass = jPasswordFieldPass.getPassword();
        String password = String.copyValueOf(pass);

        if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti polje password!", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
        }

        if(jLabelPrikaziPass.getText().equals("")){
            jPasswordFieldPass.setEchoChar((char)0);
            jLabelPrikaziPass.setText("Set");
        } else {
            jPasswordFieldPass.setEchoChar('*');
            jLabelPrikaziPass.setText("");
        }
    }//GEN-LAST:event_jButtonPrikaziPassActionPerformed

    private void jButtonPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrijavaActionPerformed
        String email = jTextFieldEmail.getText();
        char[] nizPass = jPasswordFieldPass.getPassword();
        String pass = String.copyValueOf(nizPass);

        if(email.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.endsWith("@kbk.com")) {
            JOptionPane.showMessageDialog(this, "E-mail adresa se mora završavati sa @kbk.com", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
            return;
        }
        /*
        try {
            resetForme();
            validacijaForme();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
        }
        */

        Clan clan = new Clan(-1L, "", "", new Date(), "", email, pass, new Grupa());

        //Clan clan = new Clan();
        //clan.setEmail(email);
        //clan.setPassword(pass);
        //clan.setGrupa(new Grupa());
        
        ServerskiOdgovor so = Kontroler.getInstance().pronadjiClana(clan);

        if(so.isUspesnost()){
            FrmGlavnaClan formaGlavnaClan = new FrmGlavnaClan();
            
            formaGlavnaClan.pack();
            formaGlavnaClan.setVisible(true);
            
            formaGlavnaClan.setTrenutnoUlogovan((Clan) so.getOdgovor());
            SesijaClan.getInstance().setClan((Clan) so.getOdgovor());
            
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Nepostojeći član, pokušajte ponovo!!");
        }
    }//GEN-LAST:event_jButtonPrijavaActionPerformed

    private void jPasswordFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPocetna;
    private javax.swing.JButton jButtonPrijava;
    private javax.swing.JButton jButtonPrikaziPass;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPrikaziPass;
    private javax.swing.JPanel jPanelPrijava;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables

    
    
}
