/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Trener;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmPrijavljivanjeTrener extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrijavljivanjeTrener
     */
    public FrmPrijavljivanjeTrener() {
        initComponents();
        setLocationRelativeTo(null);

        jLabelPrikaziPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrijava = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonPrikaziPass = new javax.swing.JButton();
        jButtonPrijava = new javax.swing.JButton();
        jLabelPrikaziPass = new javax.swing.JLabel();
        jButtonRegistracija = new javax.swing.JButton();
        jLabelRegistracija = new javax.swing.JLabel();
        jButtonPocetna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijavljivanje - trener");

        jPanelPrijava.setBorder(javax.swing.BorderFactory.createTitledBorder("Prijavljivanje na sistem"));
        jPanelPrijava.setToolTipText("");

        jLabelEmail.setText("email: ");

        jLabelPass.setText("password: ");

        jButtonPrikaziPass.setText("Prikaži password");
        jButtonPrikaziPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPassActionPerformed(evt);
            }
        });

        jButtonPrijava.setText("Prijavi se");
        jButtonPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrijavaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrijavaLayout = new javax.swing.GroupLayout(jPanelPrijava);
        jPanelPrijava.setLayout(jPanelPrijavaLayout);
        jPanelPrijavaLayout.setHorizontalGroup(
            jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(jLabelPrikaziPass, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(jButtonPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrikaziPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                        .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPass)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jPasswordFieldPass))))
                .addContainerGap())
        );
        jPanelPrijavaLayout.setVerticalGroup(
            jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrikaziPass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButtonPrikaziPass)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrijava)
                .addContainerGap())
        );

        jButtonRegistracija.setText("Registracija");
        jButtonRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistracijaActionPerformed(evt);
            }
        });

        jLabelRegistracija.setText("Nemate nalog? Registrujte se");

        jButtonPocetna.setText("Početna forma");
        jButtonPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPocetnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelRegistracija))
                    .addComponent(jPanelPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPocetna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegistracija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPocetna)
                    .addComponent(jButtonRegistracija))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPassActionPerformed
        char[] pass = jPasswordFieldPass.getPassword();
        String password = String.copyValueOf(pass);

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti polje password!", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (jLabelPrikaziPass.getText().equals("")) {
            jPasswordFieldPass.setEchoChar((char) 0);
            jLabelPrikaziPass.setText("Set");
        } else {
            jPasswordFieldPass.setEchoChar('*');
            jLabelPrikaziPass.setText("");
        }
    }//GEN-LAST:event_jButtonPrikaziPassActionPerformed

    private void jButtonPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrijavaActionPerformed
        String email = jTextFieldEmail.getText();
        char[] nizPass = jPasswordFieldPass.getPassword();
        String pass = String.copyValueOf(nizPass);

        if (email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.endsWith("@kbk.com")) {
            JOptionPane.showMessageDialog(this, "E-mail adresa se mora završavati sa @kbk.com", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Trener trener = new Trener(-1L, "", "", email, pass, new Date());

        ServerskiOdgovor so = Kontroler.getInstance().pronadjiTrenera(trener);
        if (so.isUspesnost()) {
            JOptionPane.showMessageDialog(this, "Uspešno ste se prijavili na sistem!", "Uspešno prijavljivanje", JOptionPane.INFORMATION_MESSAGE);
            FrmGlavnaTrener glavnaFormaT = new FrmGlavnaTrener();
            glavnaFormaT.setTrenutnoUlogovan((Trener) so.getOdgovor());
            Sesija.getInstance().setTrener((Trener) so.getOdgovor());
            glavnaFormaT.pack();
            glavnaFormaT.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nepostojeći trener, pokušajte ponovo!", "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
        }

        /*
        try {
            resetForme();
            validacijaForme();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom prijavljivanja", JOptionPane.ERROR_MESSAGE);
        }
         */
    }//GEN-LAST:event_jButtonPrijavaActionPerformed

    private void jButtonRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistracijaActionPerformed
        FrmRegistrovanje formaRegistrovanje = new FrmRegistrovanje();
        formaRegistrovanje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegistracijaActionPerformed

    private void jButtonPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPocetnaActionPerformed
        FrmPocetna formaPocetna = new FrmPocetna();
        formaPocetna.pack();
        formaPocetna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPocetnaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPocetna;
    private javax.swing.JButton jButtonPrijava;
    private javax.swing.JButton jButtonPrikaziPass;
    private javax.swing.JButton jButtonRegistracija;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPrikaziPass;
    private javax.swing.JLabel jLabelRegistracija;
    private javax.swing.JPanel jPanelPrijava;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables

    
}
