/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Trener;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmRegistrovanje extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrovanje
     */
    public FrmRegistrovanje() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistrovanje = new javax.swing.JPanel();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jButtonRegistracija = new javax.swing.JButton();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jDateChooserDatum = new com.toedter.calendar.JDateChooser();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonPocetna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registracija ");

        jPanelRegistrovanje.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrovanje"));

        jLabelIme.setText("ime: ");

        jLabelPrezime.setText("prezime: ");

        jLabelEmail.setText("email: ");

        jLabelPass.setText("password: ");

        jLabelDatum.setText("datum rodjenja: ");

        jButtonRegistracija.setText("Registracija");
        jButtonRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistracijaActionPerformed(evt);
            }
        });

        jDateChooserDatum.setDateFormatString("dd.MM.yyyy");

        javax.swing.GroupLayout jPanelRegistrovanjeLayout = new javax.swing.GroupLayout(jPanelRegistrovanje);
        jPanelRegistrovanje.setLayout(jPanelRegistrovanjeLayout);
        jPanelRegistrovanjeLayout.setHorizontalGroup(
            jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrovanjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRegistrovanjeLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPass)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelPrezime)
                            .addComponent(jLabelIme)
                            .addComponent(jLabelDatum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jPasswordFieldPass)
                            .addComponent(jDateChooserDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelRegistrovanjeLayout.setVerticalGroup(
            jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrovanjeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIme)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezime)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDatum)
                    .addComponent(jDateChooserDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButtonRegistracija)
                .addContainerGap())
        );

        jButtonPocetna.setText("Početna forma");
        jButtonPocetna.setAlignmentY(0.0F);
        jButtonPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPocetnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRegistrovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPocetna)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistrovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPocetna)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistracijaActionPerformed
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        String email = jTextFieldEmail.getText();
        char[] nizPass = jPasswordFieldPass.getPassword(); //Sifra je data kao niz (osetljiv podatak), moramo da je pretvorimo u string
        String pass = String.copyValueOf(nizPass); //Sad nam je sifra string
        Date datumRodjenja = jDateChooserDatum.getDate();

        /*try {
            resetForme();
            validacijaForme(); //klijentska validacija - da li su polja prazna?
        } catch (Exception ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom registrovanja", JOptionPane.ERROR_MESSAGE);
        }
         */
        if (!email.endsWith("@kbk.com")) {
            JOptionPane.showMessageDialog(this, "E-mail adresa se mora završavati sa @kbk.com", "Greška prilikom registrovanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nizPass.length < 4) {
            JOptionPane.showMessageDialog(this, "Šifra mora imati najmanje 4 karaktera!", "Greška prilikom registrovanja", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || pass.isEmpty() || datumRodjenja == null) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška prilikom registrovanja", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            Trener t = new Trener(-1L, ime, prezime, email, pass, datumRodjenja);

            ServerskiOdgovor so = Kontroler.getInstance().zapamtiTrenera(t);

            if (so.isUspesnost()) {
                JOptionPane.showMessageDialog(this, "Sistem je uspešno zapamtio vaše podatke! Prijavite se na sistem!", "Registrovanje", JOptionPane.INFORMATION_MESSAGE);
                FrmPrijavljivanjeTrener formaPrijavljivanje = new FrmPrijavljivanjeTrener();
                formaPrijavljivanje.setVisible(true);
                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Greška, sistem ne može da zapamti vaše podatke!", "Registrovanje", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }
        }

    }//GEN-LAST:event_jButtonRegistracijaActionPerformed

    private void jButtonPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPocetnaActionPerformed
        this.dispose();
        FrmPocetna formaPocetna = new FrmPocetna();
        formaPocetna.setVisible(true);

    }//GEN-LAST:event_jButtonPocetnaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPocetna;
    private javax.swing.JButton jButtonRegistracija;
    private com.toedter.calendar.JDateChooser jDateChooserDatum;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JPanel jPanelRegistrovanje;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

}
