/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.grupa;

import domen.Grupa;
import domen.Trener;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Natasa
 */
public class FrmDodajGrupu extends javax.swing.JDialog {
    private Trener ulogovanTrener = Sesija.getInstance().getTrener();

    public void setUlogovanTrener(Trener ulogovanTrener) {
        this.ulogovanTrener = ulogovanTrener;
    }

    public Trener getUlogovanTrener() {
        return ulogovanTrener;
    }
    
    

    /**
     * Creates new form FrmDodajGrupu
     */
    public FrmDodajGrupu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        jLabelTrenerPrikaz.setText(ulogovanTrener + "");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDodavanje = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jLabelKapacitet = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldKapacitet = new javax.swing.JTextField();
        jButtonDodavanje = new javax.swing.JButton();
        jLabelTrener = new javax.swing.JLabel();
        jLabelTrenerPrikaz = new javax.swing.JLabel();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje grupe");

        jPanelDodavanje.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodavanje grupe"));

        jLabelNaziv.setText("Naziv: ");

        jLabelKapacitet.setText("Kapacitet:");

        jButtonDodavanje.setText("Dodaj grupu");
        jButtonDodavanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodavanjeActionPerformed(evt);
            }
        });

        jLabelTrener.setText("Trener: ");

        jLabelTrenerPrikaz.setText("Ime trenera");

        javax.swing.GroupLayout jPanelDodavanjeLayout = new javax.swing.GroupLayout(jPanelDodavanje);
        jPanelDodavanje.setLayout(jPanelDodavanjeLayout);
        jPanelDodavanjeLayout.setHorizontalGroup(
            jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodavanjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDodavanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDodavanjeLayout.createSequentialGroup()
                        .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelKapacitet, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                            .addComponent(jLabelTrener))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrenerPrikaz, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jTextFieldKapacitet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelDodavanjeLayout.setVerticalGroup(
            jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodavanjeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaziv)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKapacitet)
                    .addComponent(jTextFieldKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDodavanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrenerPrikaz)
                    .addComponent(jLabelTrener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButtonDodavanje)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDodavanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNazad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDodavanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonDodavanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodavanjeActionPerformed
        String naziv = jTextFieldNaziv.getText();
        String kapac = jTextFieldKapacitet.getText();
        
        if(naziv.isEmpty() || kapac.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!!");
            return;
        }
        
        int kapacitet = Integer.parseInt(kapac);
        Trener trener = ulogovanTrener;
        
        if(kapacitet > 5 || kapacitet < 1){
            JOptionPane.showMessageDialog(this, "Kapacitet grupa se kreće u intervalu od 1 do 5!!");
            return;
        }
        
        if(naziv.length() != 2){
             JOptionPane.showMessageDialog(this, "Naziv grupe su dva karaktera u formatu slovo broj (na primer: P1)!");
            return;
        }
        
        Grupa grupa = new Grupa(-1L, naziv, kapacitet, 0, trener); //broj članova 0 jer je nova
        ServerskiOdgovor so = Kontroler.getInstance().zapamtiGrupu(grupa);
        JOptionPane.showMessageDialog(this, so.getPoruka());
        if(so.isUspesnost()){
            JOptionPane.showMessageDialog(this, "Dodata je nova grupa!!");
            reset();
        } else{
            JOptionPane.showMessageDialog(this, "Nova grupa nije dodata!!");
        }
                
    }//GEN-LAST:event_jButtonDodavanjeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodavanje;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JLabel jLabelKapacitet;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelTrener;
    private javax.swing.JLabel jLabelTrenerPrikaz;
    private javax.swing.JPanel jPanelDodavanje;
    private javax.swing.JTextField jTextFieldKapacitet;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        jTextFieldNaziv.setText("");
        jTextFieldKapacitet.setText("");
    }
}
